from . import views
from django.urls import path

urlpatterns = [
     # path('', views.index),
     path('question/<int:id>', views.question, name='question'),
     path('question-list', views.question_list, name='question_list'),
     path('question/<int:id>/like', views.like_question, name='like_question'),
     path('question/<int:id>/unlike', views.unlike_question, name='unlike_question'),
     path('question/create', views.post_question, name='post_question'),
     path('question/<int:id>/edit', views.edit_question, name='edit_question'),
     path('my-questions', views.my_questions, name='my_questions'),
     path('my-question-list', views.my_question_list, name='my_question_list'),
     path('questions', views.questions, name='questions'),
     path('question/<int:id>/answer/create',
          views.answer_create, name='answer_create'),
     path('answer/<int:id>/vote', views.vote_answer, name='vote_answer'),
     path('answer/<int:id>/edit', views.edit_answer, name='edit_answer'),
     path('answer/<int:id>/unvote', views.unvote_answer, name='unvote_answer'),
     path('blog/create', views.blog_create, name="blog_create"),
     path('blog/<int:id>/edit', views.blog_edit, name='blog_edit'),
     path('answer/<int:id>/endorse', views.endorse_answer, name='endorse_answer'),
     path('answer/<int:id>/unendorse',
          views.unendorse_answer, name='unendorse_answer'),
     path('answer/<int:id>/disapprove',
          views.disapprove_answer, name='disapprove_answer'),
     path('answer/<int:id>/undisapprove',
          views.undisapprove_answer, name='undisapprove_answer'),

     path('looking-for-mentor',
          views.looking_for_mentor, name='looking_for_mentor'),
     path('looking-for-mentor-list',
          views.looking_for_mentor_list, name='looking_for_mentor_list'),
     path('looking-for-mentor/create', views.post_looking_for_mentor, name='post_looking_for_mentor'),
     path('looking-for-work',
          views.looking_for_work, name='looking_for_work'),
     path('looking-for-work-list',
          views.looking_for_work_list, name='looking_for_work_list'),
     path('looking-for-work/create', views.post_looking_for_work, name='post_looking_for_work'),
]
